## This function takes in two the dataframes from individual studies
## and formats the columns etc.

formatData <- function(sites, species){
  
  sites['Study_Name'] <- as.factor(sites['Study_Name'])

  sites['Study_Name'] <- as.factor(sites['Study_Name'])
  sites['Site_Name'] <- as.factor(sites['Site_Name'])
  sites['Observational?'] <- as.factor(sites['Observational?'])
  sites['Latitude (decimal degrees)'] <- as.numeric(sites['Latitude (decimal degrees)'])
  sites['Longitude (Decimal Degrees)'] <- as.numeric(sites['Longitude (Decimal Degrees)'])
  sites['Altitude (m)'] <- as.numeric(sites['Altitude (m)'])
  sites['Country'] <- as.factor(sites['Country'])
  sites['Sample_StartDate_Month'] <- as.integer(sites['Sample_StartDate_Month'])
  sites['Sample_StartDate_Year'] <- as.integer(sites['Sample_StartDate_Year'])
  sites['Sample_EndDate_Month'] <- as.integer(sites['Sample_EndDate_Month'])
  sites['Sample_EndDate_Year'] <- as.integer(sites['Sample_EndDate_Year'])
  sites['ExtractionMethod'] <- as.factor(sites['ExtractionMethod'])
  sites['Sampled Area'] <- as.integer(sites['Sampled Area'])
  sites['Sampled Area Unit'] <- as.factor(sites['Sampled Area Unit'])
  sites['Sample Effort'] <- as.numeric(sites['Sample Effort'])
  sites['PH'] <- as.numeric(sites['PH'])
  sites['PH Collection Method'] <- as.factor(sites['PH Collection Method'])
  sites['Organic Carbon (%)'] <- as.numeric(sites['Organic Carbon (%)'])
  sites['Soil Organic Matter (%)'] <- as.numeric(sites['Soil Organic Matter (%)'])
  sites['C/N ratio'] <- as.numeric(sites['C/N ratio'])                                 
  sites['Sand (%)'] <- as.numeric(sites['Sand (%)'])                                  
  sites['Silt (%)'] <- as.numeric(sites['Silt (%)'])
  sites['Clay (%)'] <- as.numeric(sites['Clay (%)'])
  sites['Soil Moisture(%)'] <- as.numeric(sites['Soil Moisture(%)'])
  sites['Water Holding Capacity % (versus dry weight)'] <- as.numeric(sites['Water Holding Capacity % (versus dry weight)'])
  sites['SoilType'] <- as.factor(sites['SoilType'])                                 
  sites['LandUse'] <- as.factor(sites['LandUse'])                              
  sites['HabitatCover'] <- as.factor(sites['HabitatCover'])
  sites['SpeciesRichness'] <- as.numeric(sites['SpeciesRichness'])                          
  sites['SpeciesRichnessUnit'] <- as.factor(sites['SpeciesRichnessUnit'])
  sites['Habitat as described'] <- as.factor(sites['Habitat as described'])              
  sites['ID'] <- as.factor(sites['ID'])
  sites['WetBiomass']   <- as.numeric(sites['WetBiomass'])
  sites['WetBiomassUnits'] <- as.factor(sites['WetBiomassUnits'])
  
  species['Study_ID'] <- as.factor(species['Study_ID'])
  species['Site_Name'] <- as.factor(species['Site_Name'])
  species['SpeciesBinomial'] <- as.factor(species['SpeciesBinomial'])
  species['MorphospeciesID'] <- as.factor(species['MorphospeciesID'])
  species['Genus'] <- as.factor(species['Genus'])
  species['Family'] <- as.factor(species['Family'])
  species['LifeStage'] <- as.factor(species['LifeStage'])
  species['Native/Non-native'] <- as.factor(species['Native/Non-native'])
  species['Functional Type'] <- as.factor(species['Functional Type'])
  species['Abundance'] <- as.numeric(species['Abundance'])
  species['Abundance Unit'] <- as.factor(species['Abundance Unit'])
  species['ID'] <- as.factor(species['ID'])
  species['WetBiomass'] <- as.numeric(species['WetBiomass'])
  species['WetBiomassUnits'] <- as.factor(species['WetBiomassUnits'])
  
}